frameworkVersion: "=1.25.0"

service:
  name: comments

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-2
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${self:provider.stage}}

custom:
  defaultStage: dev
  profiles:
    dev: hunseol-dev
    prod: hunseol

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
